#include "protheus.ch"
#include "rwmake.ch"

/*/{Protheus.doc} NFLPEF01
    Configuração de Empresa e Filial por Schedule

    Cliete: Megaplasma

 @type function
 @version v1.0
 @author Eduarda Menezes
 @since 20/10/2023
 @nested-tags: Pontos de Entrada
/*/
User Function NFLPEF01(cProcesso) 
    Local aParam    := {}

    If  cProcesso == "MONNF002"         .OR.; // Sincronização NF-e via JOB
        cProcesso == "MONNF024"         .OR.; // Sincronização CT-e via JOB
        cProcesso == "SYNC_NFSE"        .OR.; // Sincronização NFSe via JOB 
        cProcesso == "NFLNFSESCHEDULE"  .OR.; // Sincronização NFSe via JOB direto
        cProcesso == "MANIFEST1"        .OR.; // Manifestação do destinatário - Ciência da operação e Confirmação da operação de forma automática
        cProcesso == "MANIFEST2"            ; // Sintoniza as tabelas de NFL_EVENTS(NFLegal) e SPED150/TSS

        // Empresa/Filial
		aAdd(aParam , { "01" , "0201" }) // 06979521000119 > 0201
		aAdd(aParam , { "01" , "0401" }) // 80319064000199 > 0401
		aAdd(aParam , { "01" , "0301" }) // 13926910000141 > 0301
		aAdd(aParam , { "01" , "0203" }) // 06979521000380 > 0203
		aAdd(aParam , { "01" , "0204" }) // 06979521000461 > 0204
		aAdd(aParam , { "01" , "0205" }) // 06979521000542 > 0205
    EndIf

Return(aParam)
