#include "rwmake.ch"
//PROGRAMA PARA GERAR DIGITIO VERIFICADOR DO BANCO REAL
USER FUNCTION DIGITO()                                 
//RECEBENDO A VARIAEL DO LAYOUT
ULTDSK:=SEE->EE_ULTDSK
//ULTDSK:=STR(ULTDSK) 
//RETITANDO CADA CARACTER
NUM2:=Substr(ULTDSK,1,1)
NUM3:=Substr(ULTDSK,2,1)
NUM4:=Substr(ULTDSK,3,1)
NUM5:=Substr(ULTDSK,4,1)
NUM6:=Substr(ULTDSK,5,1)
NUM7:=Substr(ULTDSK,6,1)
//CONVETENDO PARA NUMERO PARA PODER OPERAR EXPREÇÃO
NUM2:=VAL(NUM2)
NUM3:=VAL(NUM3)
NUM4:=VAL(NUM4)
NUM5:=VAL(NUM5)
NUM6:=VAL(NUM6)
NUM7:=VAL(NUM7)
//EXPRESÃO SOMA DA MULTIPLICAÇÃO DE CADA NUMERO PELO SEU PESO
TOTAL:=(NUM2*7)+(NUM3*3)+(NUM4*1)+(NUM5*9)+(NUM6*7)+(NUM7*3)
//SOMANDO RESUTADOA ANTERIOR PELA CONTANTE 72 REFERENTE A NOMA DA AGENCIA, CONTA, DIGITO, TIPOCONTA COM SEUS PESOS
TOTAL:=TOTAL+72
//RESUTADO DO RESTO DA DIVISÃO POR 10
TOTAL:=TOTAL%10                      
//INVERTENDO O SINAL
TOTAL:=TOTAL*-1

TOTAL:=TOTAL+10
//SE TOTAL FOR IGUAL A 10 RETORNE 0 SE NÃO PERMANESE TOTAL
TOTAL:=IF(TOTAL==10,0,TOTAL)

/*
DIGITO:=(
		 (
		  (
		   (Substr(ULTDSK,1,1)*7)+
		   (Substr(ULTDSK,2,1)*3)+
		   (Substr(ULTDSK,3,1)*1)+
		   (Substr(ULTDSK,4,1)*9)+
		   (Substr(ULTDSK,5,1)*7)+
		   (Substr(ULTDSK,6,1)*3)+72
		  )%10
		 )*-1
        )+10
 */
//DIGITO:=IF(DIGITO=10,0,DIGITO)
//MDIGITO := STR(DIGITO) 
//TOTAL:=STR(TOTAL)
//MSGBOX(TOTAL)  
RETURN(TOTAL)
