#INCLUDE "PROTHEUS.CH"
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณTK271LEG  บAutor   ณFernando Amorim    บ Data ณ  01/22/10   บฑฑ
ฑฑบPrograma  ณTK271LEG  บRevisao ณSonia Silva        บ Data ณ  23/11/17   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณEsse ponto de entrada foi criado para a altera็ใo do texto eบฑฑ
ฑฑบ          ณdas cores da Legenda do Browse de Atendimento da rotina de  บฑฑ
ฑฑบ          ณCallcenter                                                  บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ Callcenter e Faturamento                                   บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/  

User Function TK271LEG(cPasta)

Local aCores := {	{"BR_MARRON"  	,"Atendimento" },;					//"Atendimento"
					{"BR_AZUL"		,"Or็amento" },;      				//"Or็amento"
					{"BR_VERDE"    	,"Faturamento" },;					//"Faturamento"
					{"BR_VERMELHO" 	,"NF.Emitida" },;					//"NF.Emitida"
					{"BR_PRETO"    	,"Cancelado" },;					//"Cancelado"
					{"BR_BRANCO"    ,"Bloq. para Analise de Credito" }}						

Return (aCores)